---
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 4
---

## Academic positions

<font size='3' color='grey'>2022--2025</font> <br>
Postdoctoral research scientist <br>
**Institute for Phonetics and Speech Processing, Ludwig Maximilian University, Munich**

<font size='3' color='grey'>2021--2022</font> <br>
Two fixed-term part-time positions as lecturer <br> **Amsterdam Center for Language and Communication, University of Amsterdam**

<font size='3' color='grey'>2018--2022</font> <br>
PhD fellow <br> 
**Leiden University Centre for Linguistics**

<font size='3' color='grey'>2013--2017</font> <br> Various teaching and research assistant positions <br> **School of Culture and Society, Aarhus University**

## Education

<font size='3' color='grey'>2023</font> <br> **PhD** in Linguistics <br> **Leiden University**

<font size='3' color='grey'>2018</font> <br> **MA** in Linguistics <br> **Aarhus University**

<font size='3' color='grey'>2016</font> <br> **BA** in Linguistics and China Studies <br> **Aarhus University**

## Internationalization

<font size='3' color='grey'>2020</font> <br> **The Arctic University of Norway -- Tromsø** <br>
Center for Advanced Studies in Linguistics <br>
3 month research visit

<font size='3' color='grey'>2018</font> <br> **Aarhus University** <br>
Peter Skautrup Centre for Jutlandic Dialect Research <br>
2 month research visit

<font size='3' color='grey'>2017--2018</font> <br> **KU Leuven** <br>
ResMA Advanced Studies in Linguistics <br>
Full semester exchange

<font size='3' color='grey'>2016</font> <br> **Peking University** <br>
European--Chinese Language and Culture Programme <br>
Full semester exchange

## Research grants

<font size='3' color='grey'>2024</font> <br> Carlsberg Foundation Reintegration Fellowship (CF24-1380), DKK 1,899,313 (approx. €250,000) <br>
*Category-shifting Change in Real Time* (CatChaRT) <br>
(annulled due to scheduling conflict)

## Other grants and awards

<font size='3' color='grey'>2024</font> &emsp; *Journal of Phonetics* 2023 Best Early Career Scholar's Article of the Year, $250 <br>
<font size='3' color='grey'>2020</font> &emsp; William Demant Fonden travel grant, €800 (annulled due to COVID-19 outbreak) <br>
<font size='3' color='grey'>2020</font> &emsp; Leids Universiteits Fonds travel grant, €1.600 <br>
<font size='3' color='grey'>2017</font> &emsp; Aarhus University Arts travel grant, €550 <br>
<font size='3' color='grey'>2015</font> &emsp; Aarhus University Arts travel grant, €800 <br>
<font size='3' color='grey'>2015</font> &emsp; Aarhus University Linguistics Department travel grant, €200

## Service roles

#### Kellogg College

<font size='3' color='grey'>2024--</font> &emsp; &emsp; &ensp; Governing Body member

#### Aarhus University

<font size='3' color='grey'>2017</font> &emsp; &emsp; &emsp; Grade appeal board member <br>
<font size='3' color='grey'>2013--2018</font> &emsp;&thinsp; Freshers week organization and assistance <br>
<font size='3' color='grey'>2014</font> &emsp; &emsp; &emsp; Mentoring for new undergraduate students

#### Other roles

<font size='3' color='grey'>2021--2023</font> &emsp;&thinsp; Board member of [*Student Organization of Linguistics in Europe*](https://www.universiteitleiden.nl/en/events/series/sole){target='_blank'} <br>
<font size='3' color='grey'>2014</font> &emsp; &emsp; &emsp; Co-founder and editor of [*Skrifter om Samtalegrammatik*](https://samtalegrammatik.dk/tidsskrift){target="_blank"} <br>
<font size='3' color='grey'>2013--2018</font> &emsp;&thinsp; Wed editor of [samtalegrammatik.dk](https://samtalegrammatik.dk){target="_blank"}

## Conference and workshop organization

*Lookiiiiiiiiiiing at stylised sustained prosody around Australia* <br>
Special session of *Australian Linguistic Society* 58 hosted at McGriffith University, 2--5 December, 2025 <br> Co-organized with Kathleen Jepson and John Mansfield

*Phonetics and Phonology in Denmark* 4 <br>
University of Copenhagen, 7--8 October, 2024 <br>
Co-organized with Nicolai Pharao and Anna Jespersen

*How segments influence prosody in the languages of the world* <br>
Special session of *Speech Prosody* hosted at Leiden University, 2--5 July, 2024 <br> Co-organized with Menghui Shi

*Conference of the Student Organization of Linguistics in Europe* 29 <br>
Digital meeting hosted at Leiden University, 26--28 January, 2021 <br>
Member of organizing committee

*Nordic Interdisciplinary Conference on Discourse and Interaction* 5 <br>
Aarhus University, 21--23 November, 2018 <br>
Student assistant

*Bias in Auditory Perception* <br>
Aarhus University, 18--20 September, 2015 <br>
Student assistant

## Reviewing

#### Funding applications

National Science Centre Poland, OPUS-26 scheme (2024)

#### Journal articles

*Computational Intelligence and Neuroscience* (2022) <br>
*Glossa* (2021) <br>
*Journal of Linguistics* (2025) <br>
*Journal of Phonetics* (2025) <br>
*Journal of the Acoustical Society of America* (2024 x 2) <br>
*Laboratory Phonology* (2023) <br>
*Languages* (2024, 2025 x 2) <br>
*Nydanske Sprogstudier* (2023) <br>
*Ord & Sag* (2024) <br>
*Psychonomic Bulletin & Review* (2024)

#### Book chapters

Brill (2024) <br>
Oxford University Press (2025) <br>
Springer (2023)

#### Proceedings articles

*International Congress of Phonetic Sciences* (2023) <br>
*Interspeech* (2025) <br>
*Møderne om udforskningen af dansk sprog* (2019, 2021)

#### Conference abstracts

*Australian Linguistic Society* (2025) <br>
*Conference of the Student Organization for Linguistics in Europe* (2023) <br>
*International Conference on Tone and Intonation* (2025) <br>
*Laboratory Phonology* (2022) <br>
*Phonology in the Nordic Countries* (2021)

## Affiliated research networks

<font size='3' color='grey'>2022--2023</font> &emsp;&thinsp; [Empirical Foundations of Phonology (EmpiPhon)](https://aclc.uva.nl/content/research-groups/empiphon/empiphon.html){target="_blank"} <br>
<font size='3' color='grey'>2020--2022</font> &emsp;&thinsp; Open Science Community, Leiden <br>
<font size='3' color='grey'>2020--2021</font> &emsp;&thinsp; Tromsø/Verona phonology circle <br>
<font size='3' color='grey'>2017--</font> &emsp; &emsp; &ensp; [Sounds of Language and Speech](https://soundsoflanguageandspeech.wordpress.com/){target="_blank"} (Aarhus University) <br>
<font size='3' color='grey'>2015</font> &emsp; &emsp; &emsp; Danish-accented Chinese (Aarhus University) <br>
<font size='3' color='grey'>2013--2018</font> &emsp;&thinsp; Danish Talk-in-Interaction (DanTiN)

## Languages

**Danish**: Native

**English**: Full professional proficiency

**Dutch**: Passive proficiency very high, active proficiency good <br>
Coursework to B1 level in 2018--2019

**German**: Passive proficiency very high, active proficiency decent <br>
3 years of elementary school courses in 2005--2008

**Standard Chinese**: Decent reading, basic passive and communicative proficiency <br>
Coursework to B2 level in 2014--2016

**Norwegian**: Fluent reading and very high passive proficiency

**Swedish**: Near-fluent reading and decent passive proficiency

**Icelandic**: Basic reading skills <br>
Followed intense summer school (2015)

**French**: Basic reading skills

**Castilian Spanish**: Very low proficiency <br>
3 years of high school courses (2008--2011)

**Arabic**: Some passive knowledge but no proficiency <br>
Followed evening school course (2014)

## Coding and technical skills

`R`: High proficiency <br>
Data processing, plotting, acoustic analysis, typesetting (with RMarkdown and Quarto), package preparation and maintenance, and statistical analysis (see below)

`Praat`: High proficiency <br>
Acoustic analysis, scripting

`LaTeX`: Decent proficiency <br>
Typesetting, figures, plotting

`Git`: Decent proficiency <br>
Version control, collaborative projects

`VBA`: Basic proficiency <br>
Data preprocessing

`bash`: Basic proficiency <br>
Various types of task automatization

`HTML`: Basic proficiency

`Python`: Basic proficiency

## Statistical expertise

Linear and logistic (mixed) models <br>
Generalized additive (mixed) models <br>
Functional (mixed) models <br>
Growth curve analysis <br>
(Functional) principal component analysis <br>
Multiple correspondence analysis

## Teaching

### Full term courses

#### Ludwig Maximilian University, Munich

<font size='3' color='grey'>2023</font> <br>
*Phonetics and statistics* <br>
BA3 Phonetics and Speech Processing <br>
Taught seminars, graded weekly exercises <br>
Course coordinator: James Kirby

#### University of Amsterdam

<font size='3' color='grey'>2022</font> <br>
*Introduction to linguistics* <br>
BA1 Linguistics <br>
Taught seminars (two groups), graded final presentations <br>
Course coordinator: Enoch O. Aboh

<font size='3' color='grey'>2021</font> <br>
*Phonetics* <br>
BA1 Linguistics <br>
Taught seminars (two groups) in a hybrid format, graded weekly exercises <br>
Course coordinator: Marijn van 't Veer <br>
*Nominated for the Faculty of Humanities Education Award 2022*

<font size='3' color='grey'>2021</font> <br>*Phonology* <br>
BA2 Linguistics <br>
Taught seminars in a hybrid format, graded exercises and final presentations <br>
Course coordinator: Silke Hamann <br>
*Nominated for the Faculty of Humanities Education Award 2022*

#### Leiden University

<font size='3' color='grey'>2022</font> <br>
*Words, sentences, and sounds in interaction* <br>
BA3 English Language & Culture <br>
Co-taught and co-coordinated with Janet Grijzenhout

<font size='3' color='grey'>2022</font> <br>
*Analyzing English words and sounds* <br>
BA1 English Language & Culture <br>
Taught seminars (two groups) and gave one lecture <br>
Course coordinators: Bert Botma and Marion Elenbaas

<font size='3' color='grey'>2019--2021</font> <br>*The phonetics of English* <br>
BA1 English Language & Culture <br>
2019: Taught seminars <br>
2020: Taught seminars (three groups in person, one group online) and gave one online lecture <br>
2021: Taught seminars in the first block <br>
Course coordinator: Bert Botma

#### Aarhus University

<font size='3' color='grey'>2016</font> <br>*Understanding linguistics* <br>
BA1 Linguistics <br>
Taught seminars (two groups) <br>
Course coordinator: William McGregor

<font size='3' color='grey'>2014</font> <br>*Structure, meaning, and use* <br>
BA2 Linguistics <br>
Teaching assistant, gave feedback on assignments <br>
Course coordinator: Jan Rijkhoff

<font size='3' color='grey'>2014</font> <br>
*Danish and the languages of the World* <br>
BA1 Linguistics <br>
Teaching assistant, gave feedback on assignments <br>
Course coordinator: Line Krogager Andersen

<font size='3' color='grey'>2013</font> <br>*Phonetics and phonology* <br>
BA1 Linguistics <br>
Taught seminars (three groups), graded assignments <br>
Course coordinator: Marjoleine Sloos

### Workshops

<font size='3' color='grey'>2024</font> <br>*Plotting acoustics data with the* `praatpicture` *R library and Shiny app* <br>
3-hour workshop <br>
*Phonetics and Phonology in Denmark* 4, University of Copenhagen

<font size='3' color='grey'>2018</font> <br>
*Skriftsprog vs talesprog* <br>
4-hour workshop <br>
Holstebro Gymnasium

<font size='3' color='grey'>2017</font> <br>*Acoustics and Praat* <br>
3-hour workshop <br>
Department of Linguistics, Aarhus University

<font size='3' color='grey'>2017</font> <br>
*DanTiN: Danish Talk-in-Interaction* <br>
4-hour workshop <br>
*Herning Sprogfestival*, Herning Gymnasium

### Guest lectures

<font size='3' color='grey'>2021--2022</font> <br>*Advanced phonology 2* <br>
MA Linguistics, Leiden University <br>
Course coordinator: Bert Botma

<font size='3' color='grey'>2020--2022</font> <br>*Data management* <br>
Centre for Linguistics graduate school, Leiden University <br>
Course coordinators: Fieke Schoots and Kristina Hettne

### Evaluation

<font size='3' color='grey'>2021</font> &emsp; Two BA theses in BA English Language & Culture, Leiden University